/*
VOICEVOX Engine

VOICEVOXの音声合成エンジンです。

API version: latest
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package voicevox

import (
	"encoding/json"
)

// checks if the SpeakerInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpeakerInfo{}

// SpeakerInfo 話者の追加情報
type SpeakerInfo struct {
	Policy     string      `json:"policy"`
	Portrait   string      `json:"portrait"`
	StyleInfos []StyleInfo `json:"style_infos"`
}

// NewSpeakerInfo instantiates a new SpeakerInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpeakerInfo(policy string, portrait string, styleInfos []StyleInfo) *SpeakerInfo {
	this := SpeakerInfo{}
	this.Policy = policy
	this.Portrait = portrait
	this.StyleInfos = styleInfos
	return &this
}

// NewSpeakerInfoWithDefaults instantiates a new SpeakerInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpeakerInfoWithDefaults() *SpeakerInfo {
	this := SpeakerInfo{}
	return &this
}

// GetPolicy returns the Policy field value
func (o *SpeakerInfo) GetPolicy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value
// and a boolean to check if the value has been set.
func (o *SpeakerInfo) GetPolicyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Policy, true
}

// SetPolicy sets field value
func (o *SpeakerInfo) SetPolicy(v string) {
	o.Policy = v
}

// GetPortrait returns the Portrait field value
func (o *SpeakerInfo) GetPortrait() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Portrait
}

// GetPortraitOk returns a tuple with the Portrait field value
// and a boolean to check if the value has been set.
func (o *SpeakerInfo) GetPortraitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Portrait, true
}

// SetPortrait sets field value
func (o *SpeakerInfo) SetPortrait(v string) {
	o.Portrait = v
}

// GetStyleInfos returns the StyleInfos field value
func (o *SpeakerInfo) GetStyleInfos() []StyleInfo {
	if o == nil {
		var ret []StyleInfo
		return ret
	}

	return o.StyleInfos
}

// GetStyleInfosOk returns a tuple with the StyleInfos field value
// and a boolean to check if the value has been set.
func (o *SpeakerInfo) GetStyleInfosOk() ([]StyleInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.StyleInfos, true
}

// SetStyleInfos sets field value
func (o *SpeakerInfo) SetStyleInfos(v []StyleInfo) {
	o.StyleInfos = v
}

func (o SpeakerInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpeakerInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["policy"] = o.Policy
	toSerialize["portrait"] = o.Portrait
	toSerialize["style_infos"] = o.StyleInfos
	return toSerialize, nil
}

type NullableSpeakerInfo struct {
	value *SpeakerInfo
	isSet bool
}

func (v NullableSpeakerInfo) Get() *SpeakerInfo {
	return v.value
}

func (v *NullableSpeakerInfo) Set(val *SpeakerInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableSpeakerInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableSpeakerInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpeakerInfo(val *SpeakerInfo) *NullableSpeakerInfo {
	return &NullableSpeakerInfo{value: val, isSet: true}
}

func (v NullableSpeakerInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpeakerInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
