/*
VOICEVOX Engine

VOICEVOXの音声合成エンジンです。

API version: latest
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package voicevox

import (
	"encoding/json"
)

// checks if the LibrarySpeakerSpeakerInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LibrarySpeakerSpeakerInfo{}

// LibrarySpeakerSpeakerInfo struct for LibrarySpeakerSpeakerInfo
type LibrarySpeakerSpeakerInfo struct {
	Policy     string      `json:"policy"`
	Portrait   string      `json:"portrait"`
	StyleInfos []StyleInfo `json:"style_infos"`
}

// NewLibrarySpeakerSpeakerInfo instantiates a new LibrarySpeakerSpeakerInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLibrarySpeakerSpeakerInfo(policy string, portrait string, styleInfos []StyleInfo) *LibrarySpeakerSpeakerInfo {
	this := LibrarySpeakerSpeakerInfo{}
	this.Policy = policy
	this.Portrait = portrait
	this.StyleInfos = styleInfos
	return &this
}

// NewLibrarySpeakerSpeakerInfoWithDefaults instantiates a new LibrarySpeakerSpeakerInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLibrarySpeakerSpeakerInfoWithDefaults() *LibrarySpeakerSpeakerInfo {
	this := LibrarySpeakerSpeakerInfo{}
	return &this
}

// GetPolicy returns the Policy field value
func (o *LibrarySpeakerSpeakerInfo) GetPolicy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value
// and a boolean to check if the value has been set.
func (o *LibrarySpeakerSpeakerInfo) GetPolicyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Policy, true
}

// SetPolicy sets field value
func (o *LibrarySpeakerSpeakerInfo) SetPolicy(v string) {
	o.Policy = v
}

// GetPortrait returns the Portrait field value
func (o *LibrarySpeakerSpeakerInfo) GetPortrait() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Portrait
}

// GetPortraitOk returns a tuple with the Portrait field value
// and a boolean to check if the value has been set.
func (o *LibrarySpeakerSpeakerInfo) GetPortraitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Portrait, true
}

// SetPortrait sets field value
func (o *LibrarySpeakerSpeakerInfo) SetPortrait(v string) {
	o.Portrait = v
}

// GetStyleInfos returns the StyleInfos field value
func (o *LibrarySpeakerSpeakerInfo) GetStyleInfos() []StyleInfo {
	if o == nil {
		var ret []StyleInfo
		return ret
	}

	return o.StyleInfos
}

// GetStyleInfosOk returns a tuple with the StyleInfos field value
// and a boolean to check if the value has been set.
func (o *LibrarySpeakerSpeakerInfo) GetStyleInfosOk() ([]StyleInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.StyleInfos, true
}

// SetStyleInfos sets field value
func (o *LibrarySpeakerSpeakerInfo) SetStyleInfos(v []StyleInfo) {
	o.StyleInfos = v
}

func (o LibrarySpeakerSpeakerInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LibrarySpeakerSpeakerInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["policy"] = o.Policy
	toSerialize["portrait"] = o.Portrait
	toSerialize["style_infos"] = o.StyleInfos
	return toSerialize, nil
}

type NullableLibrarySpeakerSpeakerInfo struct {
	value *LibrarySpeakerSpeakerInfo
	isSet bool
}

func (v NullableLibrarySpeakerSpeakerInfo) Get() *LibrarySpeakerSpeakerInfo {
	return v.value
}

func (v *NullableLibrarySpeakerSpeakerInfo) Set(val *LibrarySpeakerSpeakerInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableLibrarySpeakerSpeakerInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableLibrarySpeakerSpeakerInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLibrarySpeakerSpeakerInfo(val *LibrarySpeakerSpeakerInfo) *NullableLibrarySpeakerSpeakerInfo {
	return &NullableLibrarySpeakerSpeakerInfo{value: val, isSet: true}
}

func (v NullableLibrarySpeakerSpeakerInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLibrarySpeakerSpeakerInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
