/*
VOICEVOX Engine

VOICEVOXの音声合成エンジンです。

API version: latest
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package voicevox

import (
	"encoding/json"
)

// checks if the SupportedDevicesInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SupportedDevicesInfo{}

// SupportedDevicesInfo 対応しているデバイスの情報
type SupportedDevicesInfo struct {
	Cpu  bool `json:"cpu"`
	Cuda bool `json:"cuda"`
	Dml  bool `json:"dml"`
}

// NewSupportedDevicesInfo instantiates a new SupportedDevicesInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSupportedDevicesInfo(cpu bool, cuda bool, dml bool) *SupportedDevicesInfo {
	this := SupportedDevicesInfo{}
	this.Cpu = cpu
	this.Cuda = cuda
	this.Dml = dml
	return &this
}

// NewSupportedDevicesInfoWithDefaults instantiates a new SupportedDevicesInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSupportedDevicesInfoWithDefaults() *SupportedDevicesInfo {
	this := SupportedDevicesInfo{}
	return &this
}

// GetCpu returns the Cpu field value
func (o *SupportedDevicesInfo) GetCpu() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Cpu
}

// GetCpuOk returns a tuple with the Cpu field value
// and a boolean to check if the value has been set.
func (o *SupportedDevicesInfo) GetCpuOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cpu, true
}

// SetCpu sets field value
func (o *SupportedDevicesInfo) SetCpu(v bool) {
	o.Cpu = v
}

// GetCuda returns the Cuda field value
func (o *SupportedDevicesInfo) GetCuda() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Cuda
}

// GetCudaOk returns a tuple with the Cuda field value
// and a boolean to check if the value has been set.
func (o *SupportedDevicesInfo) GetCudaOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cuda, true
}

// SetCuda sets field value
func (o *SupportedDevicesInfo) SetCuda(v bool) {
	o.Cuda = v
}

// GetDml returns the Dml field value
func (o *SupportedDevicesInfo) GetDml() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Dml
}

// GetDmlOk returns a tuple with the Dml field value
// and a boolean to check if the value has been set.
func (o *SupportedDevicesInfo) GetDmlOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dml, true
}

// SetDml sets field value
func (o *SupportedDevicesInfo) SetDml(v bool) {
	o.Dml = v
}

func (o SupportedDevicesInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SupportedDevicesInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cpu"] = o.Cpu
	toSerialize["cuda"] = o.Cuda
	toSerialize["dml"] = o.Dml
	return toSerialize, nil
}

type NullableSupportedDevicesInfo struct {
	value *SupportedDevicesInfo
	isSet bool
}

func (v NullableSupportedDevicesInfo) Get() *SupportedDevicesInfo {
	return v.value
}

func (v *NullableSupportedDevicesInfo) Set(val *SupportedDevicesInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableSupportedDevicesInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableSupportedDevicesInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSupportedDevicesInfo(val *SupportedDevicesInfo) *NullableSupportedDevicesInfo {
	return &NullableSupportedDevicesInfo{value: val, isSet: true}
}

func (v NullableSupportedDevicesInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSupportedDevicesInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
