/*
VOICEVOX Engine

VOICEVOXの音声合成エンジンです。

API version: latest
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package voicevox

import (
	"encoding/json"
)

// checks if the MorphableTargetInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MorphableTargetInfo{}

// MorphableTargetInfo struct for MorphableTargetInfo
type MorphableTargetInfo struct {
	IsMorphable bool `json:"is_morphable"`
}

// NewMorphableTargetInfo instantiates a new MorphableTargetInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMorphableTargetInfo(isMorphable bool) *MorphableTargetInfo {
	this := MorphableTargetInfo{}
	this.IsMorphable = isMorphable
	return &this
}

// NewMorphableTargetInfoWithDefaults instantiates a new MorphableTargetInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMorphableTargetInfoWithDefaults() *MorphableTargetInfo {
	this := MorphableTargetInfo{}
	return &this
}

// GetIsMorphable returns the IsMorphable field value
func (o *MorphableTargetInfo) GetIsMorphable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsMorphable
}

// GetIsMorphableOk returns a tuple with the IsMorphable field value
// and a boolean to check if the value has been set.
func (o *MorphableTargetInfo) GetIsMorphableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsMorphable, true
}

// SetIsMorphable sets field value
func (o *MorphableTargetInfo) SetIsMorphable(v bool) {
	o.IsMorphable = v
}

func (o MorphableTargetInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MorphableTargetInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["is_morphable"] = o.IsMorphable
	return toSerialize, nil
}

type NullableMorphableTargetInfo struct {
	value *MorphableTargetInfo
	isSet bool
}

func (v NullableMorphableTargetInfo) Get() *MorphableTargetInfo {
	return v.value
}

func (v *NullableMorphableTargetInfo) Set(val *MorphableTargetInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableMorphableTargetInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableMorphableTargetInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMorphableTargetInfo(val *MorphableTargetInfo) *NullableMorphableTargetInfo {
	return &NullableMorphableTargetInfo{value: val, isSet: true}
}

func (v NullableMorphableTargetInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMorphableTargetInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
