/*
VOICEVOX Engine

VOICEVOXの音声合成エンジンです。

API version: latest
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package voicevox

import (
	"encoding/json"
)

// checks if the DownloadableLibrary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DownloadableLibrary{}

// DownloadableLibrary ダウンロード可能な音声ライブラリの情報
type DownloadableLibrary struct {
	Name        string           `json:"name"`
	Uuid        string           `json:"uuid"`
	Version     string           `json:"version"`
	DownloadUrl string           `json:"download_url"`
	Bytes       int32            `json:"bytes"`
	Speakers    []LibrarySpeaker `json:"speakers"`
}

// NewDownloadableLibrary instantiates a new DownloadableLibrary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDownloadableLibrary(name string, uuid string, version string, downloadUrl string, bytes int32, speakers []LibrarySpeaker) *DownloadableLibrary {
	this := DownloadableLibrary{}
	this.Name = name
	this.Uuid = uuid
	this.Version = version
	this.DownloadUrl = downloadUrl
	this.Bytes = bytes
	this.Speakers = speakers
	return &this
}

// NewDownloadableLibraryWithDefaults instantiates a new DownloadableLibrary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDownloadableLibraryWithDefaults() *DownloadableLibrary {
	this := DownloadableLibrary{}
	return &this
}

// GetName returns the Name field value
func (o *DownloadableLibrary) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DownloadableLibrary) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DownloadableLibrary) SetName(v string) {
	o.Name = v
}

// GetUuid returns the Uuid field value
func (o *DownloadableLibrary) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *DownloadableLibrary) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *DownloadableLibrary) SetUuid(v string) {
	o.Uuid = v
}

// GetVersion returns the Version field value
func (o *DownloadableLibrary) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *DownloadableLibrary) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *DownloadableLibrary) SetVersion(v string) {
	o.Version = v
}

// GetDownloadUrl returns the DownloadUrl field value
func (o *DownloadableLibrary) GetDownloadUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DownloadUrl
}

// GetDownloadUrlOk returns a tuple with the DownloadUrl field value
// and a boolean to check if the value has been set.
func (o *DownloadableLibrary) GetDownloadUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DownloadUrl, true
}

// SetDownloadUrl sets field value
func (o *DownloadableLibrary) SetDownloadUrl(v string) {
	o.DownloadUrl = v
}

// GetBytes returns the Bytes field value
func (o *DownloadableLibrary) GetBytes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Bytes
}

// GetBytesOk returns a tuple with the Bytes field value
// and a boolean to check if the value has been set.
func (o *DownloadableLibrary) GetBytesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bytes, true
}

// SetBytes sets field value
func (o *DownloadableLibrary) SetBytes(v int32) {
	o.Bytes = v
}

// GetSpeakers returns the Speakers field value
func (o *DownloadableLibrary) GetSpeakers() []LibrarySpeaker {
	if o == nil {
		var ret []LibrarySpeaker
		return ret
	}

	return o.Speakers
}

// GetSpeakersOk returns a tuple with the Speakers field value
// and a boolean to check if the value has been set.
func (o *DownloadableLibrary) GetSpeakersOk() ([]LibrarySpeaker, bool) {
	if o == nil {
		return nil, false
	}
	return o.Speakers, true
}

// SetSpeakers sets field value
func (o *DownloadableLibrary) SetSpeakers(v []LibrarySpeaker) {
	o.Speakers = v
}

func (o DownloadableLibrary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DownloadableLibrary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["uuid"] = o.Uuid
	toSerialize["version"] = o.Version
	toSerialize["download_url"] = o.DownloadUrl
	toSerialize["bytes"] = o.Bytes
	toSerialize["speakers"] = o.Speakers
	return toSerialize, nil
}

type NullableDownloadableLibrary struct {
	value *DownloadableLibrary
	isSet bool
}

func (v NullableDownloadableLibrary) Get() *DownloadableLibrary {
	return v.value
}

func (v *NullableDownloadableLibrary) Set(val *DownloadableLibrary) {
	v.value = val
	v.isSet = true
}

func (v NullableDownloadableLibrary) IsSet() bool {
	return v.isSet
}

func (v *NullableDownloadableLibrary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDownloadableLibrary(val *DownloadableLibrary) *NullableDownloadableLibrary {
	return &NullableDownloadableLibrary{value: val, isSet: true}
}

func (v NullableDownloadableLibrary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDownloadableLibrary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
